global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
        labels:
          application: 'user-service'

  - job_name: 'seating-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['seating-service:8082']
        labels:
          application: 'seating-service'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:4003']
        labels:
          application: 'order-service'

  - job_name: 'payment-service' 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-service:4004']
        labels:
          application: 'payment-service'

  - job_name: 'catalog-service'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['catalog-service:4001']
        labels:
          application: 'catalog-service'